spring.application.name=potato-billing
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/potato_billing
spring.datasource.username=postgres
spring.datasource.password=U$b080592
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.time-zone=Asia/Kolkata
spring.jpa.open-in-view=false
