import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import html2pdf from 'html2pdf.js';
import './style.css';

const API='http://localhost:8080/api';
const SHOP={name:'M/S. MAJA POTATO CHIPS',address:'Your Shop पत्ता, Maharashtra',gstin:'GSTIN: __________________',mobile:'Mobile No: __________________'};
const PRODUCTS=[
 {name:'साधे बटाटा चिप्स',hsn:'',unit:'KG'},
 {name:'मसाला बटाटा चिप्स',hsn:'',unit:'KG'},
 {name:'पेरी पेरी बटाटा चिप्स',hsn:'',unit:'KG'},
 {name:'सॉल्टेड बटाटा चिप्स',hsn:'',unit:'KG'},
 {name:'केळी चिप्स',hsn:'',unit:'KG'}
];
const money=n=>Number(n||0).toFixed(2);

function App(){const [tab,setTab]=useState('bill'),[bills,setBills]=useState([]),[employees,setEmployees]=useState([]),[salary,setSalary]=useState([]),[raw,setRaw]=useState([]),[msg,setMsg]=useState('');
 const load=async()=>{try{setBills(await (await fetch(API+'/bills')).json());setEmployees(await (await fetch(API+'/employees')).json());setSalary(await (await fetch(API+'/salary')).json());setRaw(await (await fetch(API+'/raw-materials')).json());setMsg('')}catch(e){setMsg('Backend चालू आहे का तपासा.')}}; useEffect(()=>{load()},[]);
 return <div className="app"><header><div><h1>🥔 Maja Potato Chips Billing</h1><span>Billing • Customer Pending • Salary • Raw Material</span></div><button onClick={load}>↻ Refresh</button></header><nav>{[['bill','🧾 Billing'],['history','📋 Bills'],['employee','👷 Employees'],['salary','💰 Salary'],['raw','📦 Raw Material']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav><main>{msg&&<div className="msg">{msg}</div>}{tab==='bill'&&<Billing onDone={load}/>} {tab==='history'&&<History bills={bills}/>} {tab==='employee'&&<Employees employees={employees} onDone={load}/>} {tab==='salary'&&<Salary employees={employees} salary={salary} onDone={load}/>} {tab==='raw'&&<Raw raw={raw} onDone={load}/>}</main></div>}

function Billing({onDone}){
 const [f,setF]=useState({customerName:'',mobile:'',address:'',gstin:'',cgstRate:'0',sgstRate:'0',advanceAdjusted:'0',paidNow:'0'});
 const [rows,setRows]=useState(PRODUCTS.map(p=>({...p,checked:false,quantityKg:'',ratePerKg:''}))); const [summary,setSummary]=useState({pending:0,advance:0}); const [bill,setBill]=useState(null);
 const selected=useMemo(()=>rows.filter(x=>x.checked&&Number(x.quantityKg)>0),[rows]); const subtotal=selected.reduce((s,x)=>s+Number(x.quantityKg)*Number(x.ratePerKg||0),0); const cgst=subtotal*Number(f.cgstRate||0)/100, sgst=subtotal*Number(f.sgstRate||0)/100; const gross=subtotal+cgst+sgst; const net=Number(summary.pending||0)+gross-Number(f.advanceAdjusted||0)-Number(f.paidNow||0);
 const lookup=async()=>{if(!f.mobile)return;try{const r=await fetch(`${API}/bills/customer-summary?mobile=${encodeURIComponent(f.mobile)}`);if(r.ok){const s=await r.json();setSummary(s);setF(v=>({...v,customerName:v.customerName||s.name||'',address:v.address||s.address||''}));}}catch{}}
 const updateRow=(i,key,val)=>setRows(rs=>rs.map((x,k)=>k===i?{...x,[key]:val}:x));
 const submit=async e=>{e.preventDefault();if(!selected.length)return alert('कमीत कमी एक product select करा आणि quantity/rate भरा.'); const body={...f,cgstRate:+f.cgstRate,sgstRate:+f.sgstRate,advanceAdjusted:+f.advanceAdjusted,paidNow:+f.paidNow,items:selected.map(x=>({description:x.name,hsn:x.hsn,quantityKg:+x.quantityKg,unit:x.unit,ratePerKg:+x.ratePerKg}))}; const r=await fetch(API+'/bills',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)return alert(await r.text());const b=await r.json();setBill(b);onDone();setSummary({pending:0,advance:0});};
 const print=()=>window.print();
 const makePdfFile=async()=>{
   const element=document.getElementById('print');
   if(!element) throw new Error('चलन not found');
   const options={margin:[10,10,10,10],filename:`${bill.billNo}.pdf`,image:{type:'jpeg',quality:0.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#ffffff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy']}};
   const blob=await html2pdf().set(options).from(element).outputPdf('blob');
   return new File([blob],`${bill.billNo}.pdf`,{type:'application/pdf'});
 };
 const whatsapp=async()=>{
   if(!bill)return;
   try{
     const file=await makePdfFile();
     const shareData={title:`चलन ${bill.billNo}`,text:`${SHOP.name}\nचलन ${bill.billNo}\nग्राहक: ${bill.customer.name}`,files:[file]};
     if(navigator.share && (!navigator.canShare || navigator.canShare({files:[file]}))){
       await navigator.share(shareData);
       return;
     }
     const url=URL.createObjectURL(file);
     const a=document.createElement('a'); a.href=url; a.download=file.name; document.body.appendChild(a); a.click(); a.remove();
     setTimeout(()=>URL.revokeObjectURL(url),2000);
     alert('PDF तयार झाला आहे. WhatsApp उघडून हा PDF customer ला attach करा. Mobile Chrome मध्ये Share button वापरल्यास PDF थेट WhatsApp ला attach करता येईल.');
   }catch(e){
     if(e?.name==='AbortError') return;
     console.error(e);
     alert('PDF share करता आला नाही. Mobile Chrome वापरून पुन्हा प्रयत्न करा.');
   }
 };
 return <section><h2>नवीन बिल</h2><form onSubmit={submit} className="card form bill-form">
  <div className="form-title">ग्राहक माहिती</div><div className="grid"><input placeholder="ग्राहकाचे नाव *" required value={f.customerName} onChange={e=>setF({...f,customerName:e.target.value})}/><div className="lookup"><input placeholder="मोबाईल / WhatsApp" value={f.mobile} onChange={e=>setF({...f,mobile:e.target.value})}/><button type="button" onClick={lookup}>ग्राहक शोधा</button></div></div><input placeholder="पत्ता" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/><input placeholder="ग्राहक GSTIN (ऐच्छिक)" value={f.gstin} onChange={e=>setF({...f,gstin:e.target.value})}/>
  <div className="ledger"><b>मागील बाकी:</b> ₹{money(summary.pending)} &nbsp; <b>उपलब्ध अॅडव्हान्स:</b> ₹{money(summary.advance)}</div>
  <div className="form-title">उपलब्ध मालाची यादी — बिलात घ्यायच्या मालासमोर टिक करा</div>
  <div className="product-list">{rows.map((x,i)=><div className={'product-row '+(x.checked?'selected':'')} key={x.name}><label className="check"><input type="checkbox" checked={x.checked} onChange={e=>updateRow(i,'checked',e.target.checked)}/><span>{x.name}</span></label><input disabled={!x.checked} type="number" min="0.001" step="0.001" placeholder="प्रमाण (KG)" value={x.quantityKg} onChange={e=>updateRow(i,'quantityKg',e.target.value)}/><input disabled={!x.checked} type="number" min="0" step="0.01" placeholder="दर / KG ₹" value={x.ratePerKg} onChange={e=>updateRow(i,'ratePerKg',e.target.value)}/></div>)}</div>
  <div className="grid"><label>CGST %<input type="number" min="0" step="0.01" value={f.cgstRate} onChange={e=>setF({...f,cgstRate:e.target.value})}/></label><label>SGST %<input type="number" min="0" step="0.01" value={f.sgstRate} onChange={e=>setF({...f,sgstRate:e.target.value})}/></label></div>
  <div className="grid"><label>अॅडव्हान्स वजा ₹<input type="number" min="0" step="0.01" value={f.advanceAdjusted} onChange={e=>setF({...f,advanceAdjusted:e.target.value})}/></label><label>आजची भरलेली रक्कम ₹<input type="number" min="0" step="0.01" value={f.paidNow} onChange={e=>setF({...f,paidNow:e.target.value})}/></label></div>
  <div className="calculation"><div>सध्याचे बिल <b>₹{money(gross)}</b></div><div>मागील बाकी <b>₹{money(summary.pending)}</b></div><div>अॅडव्हान्स वजा <b>- ₹{money(f.advanceAdjusted)}</b></div><div>आजची भरलेली रक्कम <b>- ₹{money(f.paidNow)}</b></div><div className="grand">देय रक्कम <b>₹{money(net)}</b></div></div><button className="primary">बिल तयार करा</button>
 </form>
 {bill&&<div className="invoice-wrap"><div className="invoice" id="print"><div className="invoice-top"><div className="shop"><h2>{SHOP.name}</h2><div>{SHOP.address}</div><div>{SHOP.gstin}</div><div>{SHOP.mobile}</div></div><div className="invoice-meta"><div><b>चलन क्रमांक:</b> {bill.billNo.replace('PC-','')}</div><div><b>दिनांक:</b> {new Date(bill.billDate).toLocaleDateString('mr-IN')}</div></div></div>
 <div className="party-grid"><div><b>ग्राहक</b><div className="party-body"><b>{bill.customer.name}</b><br/>{bill.customer.address||'-'}<br/>{bill.customer.mobile&&<>Mobile: {bill.customer.mobile}<br/></>}{bill.customer.gstin&&<>GSTIN: {bill.customer.gstin}</>}</div></div><div><b>माल पाठविण्याचा पत्ता</b><div className="party-body">{bill.customer.address||'-'}</div></div></div>
 <div className="customer-ledger"><span>मागील बाकी: <b>₹{money(bill.previousPending)}</b></span><span>अॅडव्हान्स वजा: <b>₹{money(bill.advanceAdjusted)}</b></span><span>आजची भरलेली रक्कम: <b>₹{money(bill.paidNow)}</b></span></div>
 <table className="invoice-table"><thead><tr><th>अ.क्र.</th><th>मालाचे वर्णन</th><th>HSN क्रमांक</th><th>प्रमाण</th><th>एकक</th><th>दर</th><th>एकूण</th></tr></thead><tbody>{bill.items.map((it,i)=><tr key={i}><td>{i+1}</td><td>{it.description}</td><td>{it.hsn||''}</td><td>{it.quantityKg}</td><td>{it.unit}</td><td>{money(it.ratePerKg)}</td><td>{money(it.total)}</td></tr>)}{PRODUCTS.map(p=><tr className="available-row" key={'avail-'+p.name}><td></td><td>{bill.items.some(i=>i.description===p.name)?'✓ ':''}{p.name}</td><td></td><td></td><td></td><td></td><td></td></tr>)}<tr className="blank-row"><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody><tfoot><tr><td colSpan="6" className="tfoot-label">एकूण</td><td>{money(bill.total)}</td></tr></tfoot></table>
 <div className="bottom-grid"><div className="declaration"><b>घोषणा</b><p>या चलनात नमूद केलेल्या मालाची किंमत खरी असून दिलेली सर्व माहिती बरोबर आहे.</p><p>तर्फे {SHOP.name}</p><div className="signature-space">अधिकृत स्वाक्षरी</div></div><div className="tax-summary"><div><span>मागील बाकी</span><b>{money(bill.previousPending)}</b></div><div><span>CGST @ {money(bill.cgstRate)}%</span><b>{money(bill.cgstAmount)}</b></div><div><span>SGST @ {money(bill.sgstRate)}%</span><b>{money(bill.sgstAmount)}</b></div><div><span>अॅडव्हान्स वजा</span><b>- {money(bill.advanceAdjusted)}</b></div><div><span>आजची भरलेली रक्कम</span><b>- {money(bill.paidNow)}</b></div><div className="payable"><span>देय रक्कम</span><b>{money(bill.netPayable)}</b></div></div></div></div><div className="actions"><button onClick={print}>🖨️ प्रिंट / PDF सेव्ह करा</button><button onClick={whatsapp}>📎 WhatsApp वर PDF पाठवा</button></div></div>}
 </section>}

function History({bills}){return <section><h2>Recent Bills</h2><div className="card"><table><tbody><tr><th>Bill</th><th>Customer</th><th>Items</th><th>Current</th><th>Net Payable</th><th>Date</th></tr>{bills.map(b=><tr key={b.id}><td>{b.billNo}</td><td>{b.customer.name}</td><td>{b.items?.length||1}</td><td>₹{money(Number(b.total)+Number(b.cgstAmount||0)+Number(b.sgstAmount||0))}</td><td>₹{money(b.netPayable)}</td><td>{new Date(b.billDate).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table></div></section>}
function Employees({employees,onDone}){const [f,setF]=useState({name:'',mobile:'',role:'',monthlySalary:''});const save=async e=>{e.preventDefault();await fetch(API+'/employees',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,monthlySalary:+f.monthlySalary})});setF({name:'',mobile:'',role:'',monthlySalary:''});onDone()};return <section><h2>Employees</h2><form className="card form" onSubmit={save}><input required placeholder="Employee name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Mobile" value={f.mobile} onChange={e=>setF({...f,mobile:e.target.value})}/><input placeholder="Role" value={f.role} onChange={e=>setF({...f,role:e.target.value})}/><input type="number" placeholder="Monthly Salary ₹" value={f.monthlySalary} onChange={e=>setF({...f,monthlySalary:e.target.value})}/><button className="primary">Add Employee</button></form><div className="card"><table><tbody><tr><th>Name</th><th>Role</th><th>Mobile</th><th>Salary</th></tr>{employees.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.role}</td><td>{x.mobile}</td><td>₹{x.monthlySalary}</td></tr>)}</tbody></table></div></section>}
function Salary({employees,salary,onDone}){const [f,setF]=useState({employeeId:'',month:new Date().toISOString().slice(0,7),salary:'',advance:'0',deduction:'0',paid:'0'});const save=async e=>{e.preventDefault();const emp=employees.find(x=>x.id==f.employeeId);await fetch(API+'/salary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({employee:{id:+f.employeeId},month:f.month,salary:+(f.salary||emp?.monthlySalary||0),advance:+f.advance,deduction:+f.deduction,paid:+f.paid,paidDate:new Date().toISOString().slice(0,10)})});onDone()};return <section><h2>Salary</h2><form className="card form" onSubmit={save}><select required value={f.employeeId} onChange={e=>{const emp=employees.find(x=>x.id==e.target.value);setF({...f,employeeId:e.target.value,salary:emp?.monthlySalary||''})}}><option value="">Select employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="month" value={f.month} onChange={e=>setF({...f,month:e.target.value})}/><input type="number" placeholder="Salary" value={f.salary} onChange={e=>setF({...f,salary:e.target.value})}/><input type="number" placeholder="Advance" value={f.advance} onChange={e=>setF({...f,advance:e.target.value})}/><input type="number" placeholder="Deduction" value={f.deduction} onChange={e=>setF({...f,deduction:e.target.value})}/><input type="number" placeholder="Paid" value={f.paid} onChange={e=>setF({...f,paid:e.target.value})}/><button className="primary">Save Salary</button></form><div className="card"><table><tbody><tr><th>Employee</th><th>Month</th><th>Salary</th><th>Advance</th><th>Paid</th></tr>{salary.map(x=><tr key={x.id}><td>{x.employee.name}</td><td>{x.month}</td><td>₹{x.salary}</td><td>₹{x.advance}</td><td>₹{x.paid}</td></tr>)}</tbody></table></div></section>}
function Raw({raw,onDone}){const [f,setF]=useState({name:'',unit:'kg'});const [add,setAdd]=useState({});const save=async e=>{e.preventDefault();await fetch(API+'/raw-materials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,stock:0,lastPurchaseRate:0})});setF({name:'',unit:'kg'});onDone()};const stock=async r=>{const q=+(add[r.id]||0);if(!q)return;await fetch(`${API}/raw-materials/${r.id}/stock?quantity=${q}&rate=0`,{method:'PUT'});setAdd({...add,[r.id]:''});onDone()};return <section><h2>Raw Material</h2><form className="card form inline" onSubmit={save}><input required placeholder="Material name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Unit (kg/L/pcs)" value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}/><button className="primary">Add</button></form><div className="card"><table><tbody><tr><th>Material</th><th>Unit</th><th>Stock</th><th>Add Stock</th></tr>{raw.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.unit}</td><td>{r.stock}</td><td><input className="small" type="number" step="0.001" value={add[r.id]||''} onChange={e=>setAdd({...add,[r.id]:e.target.value})}/><button onClick={()=>stock(r)}>+ Add</button></td></tr>)}</tbody></table></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
